lang1: en
lang2: cn
dict_path: ../data/dict/ch_en_dict.dat
weight_MI: 30.0  # InfoCTM mutual information weight for ECNews

# XTRA weights for ECNews
weight_InfoNCE: 80
weight_beta: 7
weight_cluster: 10
